[AP-656] Use session metadata token
Change-Id: I34d262b1c6be07cd562ecd41c5d7df812d7d2feb

diff --git a/4-Dockerfile.clj-img b/4-Dockerfile.clj-img
--- a/4-Dockerfile.clj-img
+++ b/4-Dockerfile.clj-img
@@ -43,6 +43,7 @@ COPY --chown=build:build ext/deps.edn /home/build/.clojure/deps.edn
 COPY --chown=build:build ext/DEV.edn /home/build/.clojure/DEV.edn
 COPY --chown=build:build ext/PROD.edn /home/build/.clojure/PROD.edn
 
+COPY --chown=build:build ext/build.clj /home/build/build.clj
 
 ONBUILD RUN sed -i 's/${MAIN_CLASS}/'${MAIN_CLASS}'/g' /home/build/.clojure/deps.edn
 ONBUILD RUN cat /home/build/.clojure/deps.edn
@@ -54,15 +55,18 @@ ONBUILD COPY --chown=build:build "${ROOT_DIR_E}resources" resources
 ONBUILD COPY --chown=build:build "${ROOT_DIR_E}test" test 
 COPY --chown=build:build ext/tests.edn tests.edn
 
-ONBUILD RUN --mount=type=secret,id=settings.xml,mode=600,uid=2025,gid=2024,dst=/home/build/.m2/settings.xml set -e &&\
+
+ONBUILD RUN set -e &&\
             clojure merge.clj &&\
-            cat deps.edn &&\
             clojure -Stree &&\
+            echo "START deps.edn" &&\
+            cat deps.edn &&\
+            echo "END deps.edn" &&\
             set -e && clojure -M:test:runner &&\
             set -e && clojure -M:test:unit &&\
             echo "Running integration tests" &&\
-            curl -s http://169.254.169.254/latest/dynamic/instance-identity/document -v &&\
-            export AWS_DEFAULT_REGION="$(curl -s http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region)" &&\
+            SESSION_TOKEN=$(curl -s -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600") &&\ 
+            export AWS_DEFAULT_REGION=$(curl -s -H "X-aws-ec2-metadata-token: $SESSION_TOKEN" http://169.254.169.254/latest/dynamic/instance-identity/document | jq -r .region) &&\
             TARGET_ACCOUNT_ID="$(aws sts get-caller-identity | jq -r '.Account')" &&\
             cred=$(aws sts assume-role \
                 --role-arn arn:aws:iam::${TARGET_ACCOUNT_ID}:role/PipelineRole \
@@ -82,14 +86,23 @@ ONBUILD RUN --mount=type=secret,id=settings.xml,mode=600,uid=2025,gid=2024,dst=/
             if [[ -d "api" ]]; then \
               cd api; \
               if [[ -f "deps.edn" ]]; then \
-                clojure -Sdeps '{:deps {luchiniatwork/cambada {:mvn/version "1.0.2"}}}' \
-                  -m cambada.jar \
-                  --app-version "1.0.${BUILD_ID}" \
-                  --app-artifact-id "${PROJECT_NAME}" \
-                  --app-group-id "${ARTIFACT_ORG}" \
-                  --copy-source \
-                  -o /dist/release-libs/; \
-                cp pom.xml "/dist/release-libs/${PROJECT_NAME}-1.0.${BUILD_ID}.jar.pom.xml"; \
+                mv deps.edn deps-temp.edn &&\
+                clojure /home/build/merge.clj &&\
+                echo "START API deps.edn" &&\
+                cat deps.edn &&\
+                echo "END API deps.edn" &&\
+                out_dir=$(mktemp -d) &&\
+                echo "Compiling api jar!" &&\
+                cp ../build.clj . &&\
+                clojure -T:build jar \
+                  :main "${MAIN_CLASS}" \
+                  :group-id "${ARTIFACT_ORG}" \
+                  :artifact-id "${PROJECT_NAME}" \
+                  :version '"'1.0.${BUILD_ID}'"' \
+                  :lms true \
+                  :out '"'$out_dir'"' &&\
+                cp pom.xml /dist/release-libs/${PROJECT_NAME}-1.0.${BUILD_ID}.jar.pom.xml; \
+                cp $out_dir/${PROJECT_NAME}-1.0.${BUILD_ID}.jar /dist/release-libs/${PROJECT_NAME}-1.0.${BUILD_ID}.jar; \
                fi \
             fi &&\
             cd /home/build &&\
@@ -97,55 +110,68 @@ ONBUILD RUN --mount=type=secret,id=settings.xml,mode=600,uid=2025,gid=2024,dst=/
             ls -la /dist/release-libs/ &&\
             tree /dist | grep -v "class" &&\
             echo "Preparing extensions" &&\
-            if [[ -f resources/reflectconfig.json ]]; then \
-              jq -s "[.[][]]" \
-                  resources/reflectconfig.json \
-                  /dist/reflectconfig.json \
-                  > /dist/reflectconfig.tmp ; \
+            if [[ -f /dist/deploy/files/reflectconfig.json ]]; \
+            then jq -s "[.[][]]" \
+              /dist/deploy/files/reflectconfig.json \
+              /dist/reflectconfig.json \
+              > /dist/reflectconfig.tmp ; \
               mv /dist/reflectconfig.tmp /dist/reflectconfig.json; \
               echo "Merged extension reflectconfig.json"; fi &&\
             cat /dist/reflectconfig.json &&\
             cat deps.edn &&\
             echo "Building" &&\
-            export INIT_PACKAGES="${MAIN_CLASS%%.*},runtime,glms_util,import,batch,aws,jdk,javax,sdk,clj_aws_sign,ring,jsonista,camel_snake_kebab,lambda,clojure,next,org,com,ch,java,iso_7064,borkdude,edd,malli,${EXT_INIT_PACKAGES:-java}" &&\
-            clojure -Sverbose -M:native-image \
-             --image-name ${PROJECT_NAME} \
-             --out target \
-                -m ${MAIN_CLASS} \
-                -d deps.edn \
-                --graalvm-opt -enable-https \
-                --graalvm-opt  J-Xms${BUILD_RAM}g \
-                --graalvm-opt  J-Xmx${BUILD_RAM}g \
-                --graalvm-opt  Dcom.zaxxer.hikari.useWeakReferences=false \
-                --graalvm-opt -enable-url-protocols=https \
-                --graalvm-opt H:TraceClassInitialization=true \
-                --graalvm-opt H:ReflectionConfigurationFiles=/dist/reflectconfig.json \
-                --graalvm-opt H:+ReportExceptionStackTraces \
-                --graalvm-opt H:IncludeResources='conf/.*' \
-                --graalvm-opt H:IncludeResources='META-INF/.*' \
-                --graalvm-opt H:IncludeResources='META-INF/services/.*' \
-                --graalvm-opt H:IncludeResources='main/.*' \
-                --graalvm-opt H:IncludeResources='logback.xml' \
-                --graalvm-opt H:Log=registerResource \
-                --graalvm-opt -report-unsupported-elements-at-runtime \
-                --graalvm-opt -initialize-at-build-time=${INIT_PACKAGES} \
-                --graalvm-opt -initialize-at-run-time=org.httpkit.client \
-                --graalvm-opt -initialize-at-run-time=org.postgresql.sspi.SSPIClient \
-                --graalvm-opt -initialize-at-run-time=org.httpkit.client.SslContextFactory \
-                --graalvm-opt -initialize-at-run-time=org.httpkit.client.HttpClient &&\
-             cat target/*.build_artifacts.txt &&\
+            export INIT_PACKAGES="${MAIN_CLASS%%.*},java.rmi.server,java_http_clj,glms_util,import,batch,aws,jdk,javax,sdk,clj_aws_sign,ring,jsonista,camel_snake_kebab,lambda,clojure,next,org,com,ch,java,iso_7064,borkdude,edd,malli,${EXT_INIT_PACKAGES:-java}" &&\
+            out_dir=$(mktemp -d) &&\
+            echo "Compiling main uberjar!" &&\
+            clojure -T:build uber \
+             :main "${MAIN_CLASS}" \
+             :group-id "${ARTIFACT_ORG}" \
+             :artifact-id "${PROJECT_NAME}-standalone" \
+             :version '"'1.0.${BUILD_ID}'"' \
+             :lms true \
+             :out '"'$out_dir'"' &&\
+            ls -la /dist/release-libs &&\
+            mv pom.xml /dist/release-libs/${PROJECT_NAME}-standalone-1.0.${BUILD_ID}.jar.pom.xml &&\
+            mv $out_dir/${PROJECT_NAME}-standalone-1.0.${BUILD_ID}-standalone.jar /dist/release-libs/${PROJECT_NAME}-standalone-1.0.${BUILD_ID}.jar &&\
+            resp=$(native-image -jar /dist/release-libs/${PROJECT_NAME}-standalone-1.0.${BUILD_ID}.jar ${PROJECT_NAME} \
+                -o lambda_function \
+                --no-fallback \
+                --enable-https \
+                --gc=G1 \
+                -J-Xmx24g \
+                -Dcom.zaxxer.hikari.useWeakReferences=false \
+                -Dclojure.tools.logging.factory=lambda.logging/slf4j-json-factory \
+                --enable-url-protocols=https \
+                -H:NumberOfThreads=16 \
+                -H:TraceClassInitialization=true \
+                -H:ReflectionConfigurationFiles=/dist/reflectconfig.json \
+                -H:+ReportExceptionStackTraces \
+                -H:IncludeResources='conf/.*' \
+                -H:IncludeResources='META-INF/.*' \
+                -H:IncludeResources='META-INF/services/.*' \
+                -H:IncludeResources='main/.*' \
+                -H:IncludeResources='logback.xml' \
+                -H:Log=registerResource \
+                --report-unsupported-elements-at-runtime \
+                --initialize-at-build-time=${INIT_PACKAGES},sun.rmi.server,sun.rmi.runtime,sun.rmi.runtime,sun.rmi.server,sun.rmi.server \
+                --trace-class-initialization=clojure.lang.Compiler \
+                --trace-class-initialization=clojure.lang.RT \
+                --initialize-at-run-time=org.httpkit.client \
+                --initialize-at-run-time=org.postgresql.sspi.SSPIClient \
+                --initialize-at-run-time=org.httpkit.client.SslContextFactory \
+                --initialize-at-run-time=org.httpkit.client.HttpClient || echo "FAILED") &&\
+             echo "RESP: $resp" &&\
+             if [[ "$resp" == "FAILED" ]]; then cat /home/build/reports/traced_class_initialization*; exit 1; fi &&\
              tree &&\
+             cat /home/build/reports/traced_class_initialization* &&\
              echo "Packaging" &&\
-             cp bootstrap target/ &&\
-             cd target &&\
              mv ${PROJECT_NAME} lambda_function &&\
-             cp lambda_function /dist/lambda_function &&\
              chmod +x lambda_function &&\
-             zip /dist/${PROJECT_NAME}.zip lambda_function &&\
-             zip /dist/${PROJECT_NAME}.zip bootstrap &&\
-             mv /dist/${PROJECT_NAME}.zip /dist/${PROJECT_NAME}.jar &&\
+             zip /dist/${PROJECT_NAME}.jar lambda_function &&\
+             mv lambda_function /dist/lambda_function &&\
              rm -rf ~/.m2/repository &&\
              rm -rf target
+
 
 ONBUILD RUN tree /dist/
 
